### ISSUE TITLE
ctrl+o regex error

### ISSUE THREAD

**Issue by beowulfof** [wunderfeyd/tippse#15]
The regex for parsing the file path and line number from compilation output is defunctional, the editor opens up a new file with my/path/to/file:123 as filename.

**Comment by beowulfof** [comment]
Working regex: "\\s?([^\\n\\r]*?)\\s?\\:\\s?(\\d+)\\s?\\:\\s?(\\d+)\\s?\\:" just added another group to parse the character position. That won't be the cause of the bug, but maybe help find it.

**Comment by wunderfeyd** [comment]
Thanks for pointing me into this direction. It was a bug in the generic regular expression matching loop. The regular expression string was optimized down but still had branches in it for the unicode matching. This resulted in a multiple search even for non greedy matches but the hit flag didn't propagate the match back to the quantifier/modifier loop since only matches that were longer than the previous ones were marked.

Please update to the latest commit. Reopen if necessary.
