### ISSUE TITLE
tab/untab problems in block mode

### ISSUE THREAD

**Issue by beowulfof** [wunderfeyd/tippse#18]
Steps to reproduce:

1. select any range of lines
2. use untab twice
-->on second untab only the first selected line moves
3. use tab
-->only the first selected line moves

currently used commit: cbc7db768422e870d85e1d6425c40fcb9655b289

**Comment by wunderfeyd** [comment]
Thank you for spotting this. With the recent multi selection changes I added a flag to disallow recombining selected region to have unique selection (for example to paste the same content into the selections each). When lowering the indentation, certain areas are removed. Since the selected area wasn't allowed to combine, two or more separate selections were created. The function to lower/raise indentation is not multi selection aware to this time (but will be soon).

A region identifier was added to allow recombining of the same selections with the latest commit.

Thanks for your help. 👍
