### ISSUE TITLE
Request: Swap lines action

### ISSUE THREAD

**Issue by beowulfof** [wunderfeyd/tippse#8]
A swap lines action would be nice, e.g. [CTRL]+Up/Down moves the line upwards/downwards.

**Comment by wunderfeyd** [comment]
Thank you for your enhancement request. Before building code for this, I want to ask if the indentation should automatically corrected (if you work on code files)?

**Comment by beowulfof** [comment]
I wouldn't expect the editor to adjust the indentation, but sure, it would be a nice feature.

**Comment by wunderfeyd** [comment]
I think the implementation is done. Code needs still to be refactored, but it simple enough now to do so. Nevertheless, I found a corner case: When moving a line to a line without a return (last line) the cursor keeps hanging on the line before if it was on the return position. This is logically correct, because the return isn't moved but it might feel strange. With some additional code one could correct this. I'll add this on request or in the long run depending on work load.

Please update to the latest commit. Thank you for your suggestion.
