### ISSUE TITLE
.tippse config file not read from $home directory

### ISSUE THREAD

**Issue by beowulfof** [wunderfeyd/tippse#9]
Configuration file .tippse is only read at startup, if the editor is started in that directory. A .tippse file in the $home directory is ignored.

**Comment by wunderfeyd** [comment]
It works for me. The load order is:
* internal config embedded in config.c
* $HOME/.tippse/.tippse
* <Document path>/.tippse
* <Document path/..>/.tippse
* <Document path/../..>/.tippse
* and so on

Please note the user config is in a subdirectory in the home path. This has been done due to the fact the config files are opened from document path to the root path. When you modify a document inside your home path is automatically crawls up to your home directory and overwrites the project settings. Also it's needed to store user session data and so on in the future. 

Ideas about load order or abort conditions are welcome.

---

Tested with following setup:
`~/.tippse/.tippse`
~~~
{
	colors:{
		status:yellow
	}
}
~~~

`~/<project>/.tippse`
~~~
{
	colors:{
		text:green
	}
}
~~~

The resulting editor colors after opening a file in the project folder should be a yellow status bar and green text.

**Comment by wunderfeyd** [comment]
This issue is closed. If you think the function is not as you expected reopen the issue please.
